### PR TITLE
Introduces Ways To Get There feature

### PR DESCRIPTION
**Pull request by marcgarreau**
#### What's this PR do?
adds 'ways to get there' feature
#### Where should the reviewer start?
`WaysToGetThere`
#### How should this be manually tested?
visit `/careers/software_developer`
#### Any background context you want to provide?
this doesn't handle careers without subcareers yet.
vertical centering is hard.
the data is still junk.
#### What are the relevant tickets?
#435

### CODE REVIEW

**Comment by applegrain** [comment]
Nice :ok_hand: 
Is there a way to collapse the options and go back to the three-box view?
Vertical centering looks good!

**Comment by marcgarreau** [comment]
@applegrain nope to collapsing currently. do you expect to be able to? not hard to implement, but i didn't think it was particularly useful

**Comment by applegrain** [comment]
@marcgarreau I would expect it to be collapsible. It avoids scrolling if you want to get to the Community and Experts content (depending on how much content there is). If the other cards are going to have the same expanding behavior, perhaps the collapsed view could serve to get a snapshot of the content inside? Or be the triggers like the three subcareers boxes

**Comment by marcgarreau** [comment]
@applegrain i'm with you. the biggest question for me then is whether the user should select one of these subcareers at the top level, and it populates each section with relevant info.

damnit. i think thats how this feature should work instead. every section (experts, questions, ways to get there, jobs, meetups, etc) could easily differ with each type. one of the implications is that the parent career (i.e. software developer) just becomes an umbrella with none of its own data. that has other implications, but i think its the right way to go.

**Comment by applegrain** [comment]
@marcgarreau that sounds like the way to go! :ok_hand:

**Pull request merged**
